version: '3.0'

networks:
  kafka-zookeeper-network:
    driver: bridge

services:
  zookeeper-server:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-zookeeper-network
  kafka-server:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka-zookeeper-network
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
